repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        exclude: migrations
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.1"
    hooks:
      - id: ruff
